### ISSUE TITLE
Providing pre-generated clusters

### ISSUE THREAD

**Issue by alifarhat40** [corceslab/CHOIR#6] opened 2024-01-30 00:55 UTC
Hello,

I am trying to apply CHOIR on my precomputed clusters from a method I developed. I am working with the PBMC3k dataset in fact.

Preprocessing is exactly followed step by step from here:
https://satijalab.org/seurat/articles/pbmc3k_tutorial.html

After I perform my clustering, I obtain a list of cluster labels for each of the 2638 cells in the order they appear in the seurat object. I do not have any information about their hierarchical trees, because my method does not use trees. My question is: how do I provide this cluster_tree dataframe of my precomputed cluster labels? All I have is my cluster labels and I want to use CHOIR to correctly merge them. In scSHC and Cytocipher I can just simply pass my list of cluster labels to their functions and pop out a final answer. But I am not sure how to do the same with CHOIR. I could not find a vignette or example.
https://www.choirclustering.com/articles/CHOIR.html#providing-pre-generated-clusters

![image](https://github.com/corceslab/CHOIR/assets/32119344/b665b5a0-6df4-45ab-a1dd-b5ccb4bf7ba6)

**Comment by catpetersen** [comment] 2024-01-30 22:45
Hi! The `cluster_tree` can be generated in any way you'd like, but I've added a function to the dev branch to generate a simple hierarchical tree from provided input cluster labels based on cluster distances in a dimensionality reduction space. The output is a dataframe that can be used as input for parameter `cluster_tree`.

So install CHOIR from the dev branch, then use function `inferTree()`. Run it like this:
```
# Object cluster_IDs should be a vector of your cluster labels named with the corresponding cell ID
# Object dim_reduction should be cell embeddings from a dimensionality reduction you've previously generated
cluster_tree <- inferTree(cluster_labels = cluster_IDs, reduction = dim_reduction)
```

Alternately, without needing to install from the dev branch, you can apply two of CHOIR's hidden functions sequentially like this:
```
initial_tree <- data.frame(L1 = 1, L2 = cluster_IDs)
cluster_tree <- CHOIR:::.optimizeTree(cluster_tree = initial_tree, reduction = dim_reduction)
cluster_tree <- CHOIR:::.checkClusterLabels(cluster_tree)
```

Let me know if you run into issues with this or the subsequent steps, since this is not the primary use-case for CHOIR.

**Comment by alifarhat40** [comment] 2024-01-31 20:02
Thanks! I will try this and get back to you. 

By any chance, do you think this clustering method would work for general data as well? Or is it tailored specifically for scRNAseq data.

**Comment by catpetersen** [comment] 2024-01-31 21:55
Great!

And yes, CHOIR is compatible with any data that is in the shape of one or more cell x feature matrices. So any single-cell data (both single- and multi-omic), including single-cell RNA-seq, ATAC-seq, proteomics data, etc.

Outside of typical single-cell data, other data types that have this similar shape can also be used, though CHOIR has not been as thoroughly tested with these. For example, I've applied CHOIR to the MNIST dataset in the past (where each "cell" would be a digit sample, and the features would be the pixel values), with interesting results.

**Comment by alifarhat40** [comment] 2024-02-02 04:13
I installed the dev branch, but when running 

`cluster_tree <- inferTree(cluster_labels = cluster_IDs, reduction = dim_reduction)
`

I get the following error:
![image](https://github.com/corceslab/CHOIR/assets/32119344/98996be4-a161-45ea-8b2d-7f80230845e8)

This is a snippet of my precoputed cluster IDs. It is a vector of integer labels for each of the 2638 pbmc3k cells. 
![image](https://github.com/corceslab/CHOIR/assets/32119344/cd4b19ec-9be3-40c1-a23e-24bb4e9acbc3)


Next I try your other way:

`
initial_tree <- data.frame(L1 = 1, L2 = cluster_IDs)
cluster_tree <- CHOIR:::.optimizeTree(cluster_tree = initial_tree, reduction = dim_reduction)
cluster_tree <- CHOIR:::.checkClusterLabels(cluster_tree)
seurat_object <- pruneTree(seurat_object, cluster_tree = cluster_tree, n_cores = 1)
`

but I also get an error:
![image](https://github.com/corceslab/CHOIR/assets/32119344/41f40d69-6670-4739-8962-23a8a281d1f6)


Am I messing up a step here? Thanks in advance.

**Comment by catpetersen** [comment] 2024-02-03 02:42
Thanks for working through this! I've made some additional changes to the dev branch (so please re-install) to hopefully make starting with pre-generated clusters smoother.

First, for running `inferTree`, `cluster_labels` must be a named vector, where the names correspond to the cell IDs. This is so that the function can check that the user input cell IDs match the rownames of the cell embeddings provided for `reduction`.  The `inferTree` function now adds these same cell IDs as rownames of the output `cluster_tree`, which should stop that error you're getting when running `pruneTree`.

But since other inputs and parameters will not have been calculated or provided by the `buildTree` step of CHOIR, you'll need to provide additional inputs to the `pruneTree` function. Here's some code that extracts all of those necessary inputs for a Seurat object that has been through a standard pipeline (also requested in issue #8):

```
# Example code for a Seurat object that has been through the following steps (modify as needed)
seurat_object <- seurat_object %>%
  NormalizeData() %>%
  FindVariableFeatures() %>%
  ScaleData() %>%
  RunPCA() %>%
  FindNeighbors() %>%
  FindClusters()

#  Object cluster_labels should be a vector of your cluster labels
cluster_labels <- seurat_object@meta.data$seurat_clusters
# Make this a named vector, where the names correspond to the cell IDs
names(cluster_labels) <- colnames(seurat_object) # Assumes that cluster IDs are in the same order as cells in the object

# Extract the cell embeddings of your dimensionality reduction
dim_reduction <- seurat_object@reductions$pca@cell.embeddings

# Create cluster_tree
cluster_tree <- inferTree(cluster_labels = cluster_labels,  reduction = reduction)

# Extract variable features and input matrix for random forest classifiers
var_features <- seurat_object@assays$RNA@var.features
input_matrix <- CHOIR:::.getMatrix(seurat_object, 
                                   use_assay = "RNA", 
                                   use_slot = "data", 
                                   use_features = var_features, 
                                   verbose = TRUE)

# Extract adjacency matrices
nn_matrix <- seurat_object@graphs$RNA_nn
snn_matrix <- seurat_object@graphs$RNA_snn

# Run pruneTree
seurat_object <- pruneTree(seurat_object, 
                           cluster_tree = cluster_tree, 
                           input_matrix = input_matrix,
                           nn_matrix = nn_matrix,
                           snn_matrix = snn_matrix, # New requirement not yet reflected in online documentation
                           reduction = reduction)
```

I've tested this with two datasets myself, but please let me know if any other errors pop up. I'd also be curious how your final results compare to just running the entire default CHOIR algorithm with function `CHOIR()`.

**Comment by alifarhat40** [comment] 2024-02-03 19:57
Okay thanks! I reinstalled the new dev branch. 

1) should `cluster_labels `be a vector of characters or vector of integers?

2) I think `var_features <- seurat_object@assays$RNA@var.features` should instead be `var_features <- VariableFeatures(seurat_object, assay = "RNA")`

3) The following code gives me null for both `nn_matrix `and `snn_matrix`, because I have not run `buildtree`. Again, all I have is the cluster_labels from my own clsutering algorithm. 

``
# Extract adjacency matrices
nn_matrix <- seurat_object@graphs$RNA_nn
snn_matrix <- seurat_object@graphs$RNA_snn
``

So when I run the `pruneTree` function I get an error:

```
Error in pruneTree(seurat_object, cluster_tree = cluster_tree, input_matrix = input_matrix,  : 
  unused argument (snn_matrix = snn_matrix)
```

When I remove the variable `snn_matrix `from `pruneTree`:
`snn_matrix = snn_matrix, # New requirement not yet reflected in online documentation`

I get another error same as before:
```
Error in .validInput(cluster_tree, "cluster_tree", object) : 
Input value for 'cluster_tree' must be a dataframe or matrix in which the row names and order are identical to the cell IDs in the provided object. Please supply valid input or set to NULL.
```

![image](https://github.com/corceslab/CHOIR/assets/32119344/381f9a71-fc7a-4e0b-8f6f-f409423b768f)

**Comment by alifarhat40** [comment] 2024-02-03 20:30
After running:
`seurat_object <- FindNeighbors(seurat_object, dims = 1:10)`

I can finally extract `nn_matrix `and `snn_matrix`, but then get another error:

![image](https://github.com/corceslab/CHOIR/assets/32119344/e173053e-70cf-452d-ac03-4360c98089d3)

**Comment by catpetersen** [comment] 2024-02-05 02:32
I suspect the reinstallation might not have completed properly. Those errors should be resolved in the newest version of the dev branch. You do need the `snn_matrix` input. You can check whether you have the correct package version loaded by running `head(pruneTree, 10)`, which should give the following output (where you can see the `snn_matrix` parameter):
<img width="682" alt="Screenshot 2024-02-04 at 6 25 21 PM" src="https://github.com/corceslab/CHOIR/assets/70531665/f578badd-def8-4b4f-93dc-9081df22ba02">

To answer some of your questions:

> I do not run FindNeighbors() in my pipeline. Is that necessary?

If you want to run CHOIR in this non-standard way, then you'll have to produce all of the necessary input matrices, including the nn and snn adjacency matrices. These are all things that CHOIR would usually generate for you in the course of running the `buildTree` function.

> should cluster_labels be a vector of characters or vector of integers?

Either is fine.

Below is a reproducible example that works for me using a small dataset, see if this also errors out for you:
```
if (!requireNamespace("scRNAseq", quietly = TRUE)) BiocManager::install("scRNAseq")
library(scRNAseq)
library(Seurat)
library(CHOIR)

# Import dataset & pre-process
data_matrix <- LaMannoBrainData('mouse-adult')@assays@data$counts
colnames(data_matrix) <- seq(1:ncol(data_matrix))

seurat_object <- CreateSeuratObject(data_matrix, 
                                    min.features = 100,
                                    min.cells = 5)

seurat_object <- seurat_object %>%
  NormalizeData() %>%
  FindVariableFeatures() %>%
  ScaleData() %>%
  RunPCA() %>%
  FindNeighbors() %>%
  FindClusters()

#  Object cluster_labels should be a vector of your cluster labels
cluster_labels <- seurat_object@meta.data$seurat_clusters
# Make this a named vector, where the names correspond to the cell IDs
names(cluster_labels) <- colnames(seurat_object) # Assumes that cluster IDs are in the same order as cells in the object

# Extract the cell embeddings of your dimensionality reduction
dim_reduction <- seurat_object@reductions$pca@cell.embeddings

# Create cluster_tree
cluster_tree <- inferTree(cluster_labels = cluster_labels,  reduction = dim_reduction)

# Extract variable features and input matrix for random forest classifiers
var_features <- VariableFeatures(seurat_object)
input_matrix <- CHOIR:::.getMatrix(seurat_object, 
                                   use_assay = "RNA", 
                                   use_slot = "data", 
                                   use_features = var_features, 
                                   verbose = TRUE)

# Extract adjacency matrices
nn_matrix <- seurat_object@graphs$RNA_nn
snn_matrix <- seurat_object@graphs$RNA_snn

# Run pruneTree
seurat_object <- pruneTree(seurat_object, 
                           cluster_tree = cluster_tree, 
                           input_matrix = input_matrix,
                           nn_matrix = nn_matrix,
                           snn_matrix = snn_matrix,
                           reduction = dim_reduction)
```

As to benchmarking with ARI for real datasets, just as my personal opinion -- I don't always think that's the best approach, as it can be biased towards methods that are more similar to those used to generate the reference labels you are comparing to. But it can definitely be a starting point.

**Comment by alifarhat40** [comment] 2024-02-05 06:10
Yup. That worked. Thanks!

Running CHOIR on my precomputed clusters improved the ARI a tiny bit from 0.55 to 0.58. However, it did reduce the 15 clusters from CHOIR to 8. Here is an image of the "ground truth" from annotated pbmc3k. 

"ground truth"
![image](https://github.com/corceslab/CHOIR/assets/32119344/f72ec6b1-3611-416d-96ff-68aa81044a3e)

Here is the result after running CHOIR on my precomputed clusters from my newly developed clustering algorithm:
![image](https://github.com/corceslab/CHOIR/assets/32119344/ddb2319e-0862-4891-a6c0-baeea0047c21)

And here is scSHC on my precomputed clusters:
![image](https://github.com/corceslab/CHOIR/assets/32119344/3b16181f-8a7c-4212-b507-c9c62877dcf5)


sc-SHC was actually able to separate the upper 2 clusters for me, because my algorithm does separate them as well. So it is strange to see why CHOIR would merge them. 

1) Do you have any ideas of how I can change up some parameters in CHOIR to try and resolve this? I have a feeling CHOIR can do it, because it gave better separation from sc-SHC despite the lower ARI. CHOIR looks better. 

2) You mentioned you do not prefer to benchmark on real datasets, do you have a recommendation for how to do that? In your paper you show simulated datasets. Should I use those as well?


3) I figured I'd let you know that the functions
`seurat_object <- runCHOIRumap(seurat_object, reduction = "P0_reduction")
`
`plotCHOIR(seurat_object)
`

do not work after running CHOIR on precomputed clusters. Instead I had to run UMAP using seurat and plot them using the CHOIR clusters. Just a heads up. This is the error:
```
Error in .validInput(reduction, "reduction", list("runCHOIRumap", object, : 
Input value 'P0_reduction' for 'reduction' was not found in the provided object, please supply valid input!
3. stop("Input value '", input, "' for '", name, "' was not found in the provided object, please supply valid input!")
2. .validInput(reduction, "reduction", list("runCHOIRumap", object, 
key))
1.runCHOIRumap(seurat_object, reduction = "P0_reduction")

```
It does not bother me. I just bring it up in case it concerns you.

**Comment by catpetersen** [comment] 2024-02-05 09:12
Great! Glad that worked for you.

> Do you have any ideas of how I can change up some parameters in CHOIR to try and resolve this?

The main parameter I'd try adjusting is the `alpha` value. Other parameters to look at are `p_adjust` and `distance_awareness`. If the dataset was larger, then the `downsampling_rate` could also have an effect, but this is only relevant above 5K cells. 

When run in full, CHOIR generates multiple dimensionality reductions as it builds out the hierarchical clustering tree. A “root” dimensionality reduction encompassing all cells is followed by multiple “subtree” dimensionality reductions that each encompass a subset of the total cells. These subsetted reductions, and their accompanying sets of highly variable features allow CHOIR to pick up on more nuanced differences between cell subtypes/states. So the lack of these subsetted reductions in your case may cause CHOIR to be more conservative and merge more clusters.

> You mentioned you do not prefer to benchmark on real datasets

No, benchmarking can absolutely be done with real datasets, I just wouldn't use ARI for real datasets. There are certainly other methods that can be used to benchmark with real datasets, but I feel that benchmarking metrics that require a "ground truth" set of cell type labels are not ideal for real world data.

You are welcome to try the simulated datasets from the paper, they're available here: https://files.corces.gladstone.org/Publications/2024_Petersen_CHOIR
The `Simulated_Datasets.tar.gz` file contains the 100 simulated datasets and the `SourceData1_SimulatedData.xlsx` file contains detailed benchmarking results for CHOIR, sc-SHC, etc. including cluster labels for each cell across a variety of tested parameter settings.

And yea, for those UMAP and plotting functions, you'd have to specify a dimensionality reduction that exists in your Seurat object, instead of "P0_reduction" (which is the default name given to the dimensionality reduction calculated during the `buildTree` part of CHOIR).

I'm going to close this issue, but feel free to continue replying here if anything else comes up!

**Closed** 2024-02-05 09:12 UTC

**Comment by alifarhat40** [comment] 2024-02-05 18:03
Great. Thanks for all your help @catpetersen ! Even those 2 new clusters in the left, I am sure they could be biologically meaningful since Cytocipher discovered a similar thing in their paper. I will have to double check. 

1) could you explain a bit what `distance_awareness` is? I read the description in the preprint and function, but I am not sure how to go about selecting a value. 

2) What is the role of distances and nearest neighbor matrices in CHOIR? 

3) Other than ARI, what other metrics do you recommend for benchmarking real datasets?

4) runCHOIRumap() does not work even with setting reduction = "pca". I might be interested in the accuracy plots. The only dimensionality reduction I perform is:
`seurat_object <- RunPCA(seurat_object, features = VariableFeatures(object = seurat_object));
`
in that case what should I set variable reduction equal to?

5) Does CHOIR keep track of which precomputed clusters merged into which final clusters? Or would I have to write manual code for that? It is not big a deal if not. I can easliy match cell names with their pre and final destinations. Cytocipher provides a slankey. 

6) Lastly, and MOST important to me: you mentioned earlier that I can apply CHOIR on precomputed clusters for any kind of data. You tried it on MNIST. How would I go about trying it on data such as the ones from scikit-learn? I do not have cell names or RNA assay in seurat object. Do you have any reproducible example or prototype code to help me merge precomputed clusters on data that is not single-cell related? Will I need to run FindNeighbors in a custom seurat object for data such as below. I have an post-hoc method of merging clusters achieving the highest ARI on all these toy datasets, so I would like to see CHOIR on my precomuted clusters here. 
![image](https://github.com/corceslab/CHOIR/assets/32119344/86e9093f-3205-494c-9016-afbf607b15a8)

**Comment by catpetersen** [comment] 2024-02-09 20:49
To keep these GitHub issue threads on topic, I'll confine my answers below to questions directly related to CHOIR. For your question related to benchmarking, I'll just point back to the [pre-print](https://www.biorxiv.org/content/10.1101/2024.01.18.576317v1), which contains a lot of my thought process around how to effectively benchmark clustering methods.

> could you explain a bit what distance_awareness is? I read the description in the preprint and function, but I am not sure how to go about selecting a value.

`distance_awareness` is essentially a parameter used to make CHOIR more efficient by using a distance threshold to omit certain permutation test comparisons that we assume will just tell us that the two clusters in question should remain separate. 

Here's an example with the default value `distance_awareness = 2`. First, if cluster A has is compared to cluster B, and we've determined that cluster A and B should not be merged, we record the distance between cluster A and B in our dimensionality reduction space, let's call this distance `d`. Then, if cluster A is compared to any cluster C where the distance between cluster A and C is greater than `2d`, we just assume that these two clusters should also not be merged, and we keep them separate without running the permutation test. So, if you're fine with a somewhat longer runtime, you could increase this value, to make fewer of these assumptions and instead run more permutation tests.

> runCHOIRumap() does not work even with setting reduction = "pca"

I'll take a look at this, but this function is probably best reserved for those who generate their dimensionality reductions using CHOIR, rather than providing pre-generated reductions.

> Does CHOIR keep track of which precomputed clusters merged into which final clusters?

Yes! Check out the `records` stored under `seurat_obj@misc$CHOIR`. You can also see how the tree is pruned at each level using the `stepwise_clusters_` dataframe under `seurat_obj@misc$CHOIR$clusters`.

> How would I go about trying it on data such as the ones from scikit-learn? I do not have cell names or RNA assay in seurat object.

I'm not the best person to answer how to wrangle different types of data into a Seurat object. But you should really just need a cell x feature matrix with some sort of row and column names (e.g., 1, 2, 3..) to make this work. CHOIR is also compatible with SingleCellExperiment objects.

**Comment by alifarhat40** [comment] 2024-02-09 20:59
Much appreciated!

**Comment by alifarhat40** [comment] 2024-02-15 23:46
@catpetersen It appears CHOIR performs amazingly well on my precomputed clusters of PBMC3k dataset yet fails to keep the upper Memory vs Naive CD4 T cells separate despite the clear separation from my algorithm. My question now is: can I hard select specific clusters to NOT merge? I can fork the github repo and try implementing it myself, but would appreciate guidance on whether you think this is achievable. For example, if there are 3 clusters that I do not want them to mege with each other then I want to be able to give `pruneTree()` an additional parameter designating which precomputed clusters to specifically not merge. Thanks for your time.

**Comment by catpetersen** [comment] 2024-02-16 00:48
Glad to hear CHOIR is working well for you! No, I don't have any plans to add that feature. 

I think the easiest solution would be to manually overwrite the cluster labels with those original 3 clusters after the fact. You can then use the `compareClusters()` function to run a permutation test comparison of any two specific clusters to see if any of the other clusters should be merged into your 3 set clusters. Grab the final adjusted alpha threshold from `seurat_object@misc$CHOIR$parameters$pruneTree_parameters$adjusted_alpha` if you want to keep the same approx. significance level used in the `pruneTree` run after correction for multiple comparisons.

**Comment by alifarhat40** [comment] 2024-03-05 02:41
Hi @catpetersen 

By any chance do you know if the dev version works on a Linux cluster? Or have you made any changes to the dev branch recently that could affect running `pruneTree` on pregenerated clusters? I am running your pipeline on my pregenerated clusters on Windows and it is working great. But I can only use one core on my Windows. So I installed CHOIR on my linux today and everything runs well except when it gets to the `pruneTree` line. I even kept  n_cores = 1 to see if the issue is from there. 

```
seurat_object <- pruneTree(seurat_object, 
                           cluster_tree = cluster_tree, 
                           input_matrix = input_matrix,
                           nn_matrix = nn_matrix,
                           snn_matrix = snn_matrix, # New requirement not yet reflected in online documentation
                           reduction = dim_reduction,
                           n_cores = 1,
                           distance_awareness = 2,
                           alpha = 0.05,
                           p_adjust = 'fdr')
```


```
2024-03-04 20:32:27 : (Step 1/2) Checking inputs and preparing object..
Error in if (input > parallel::detectCores()) { : 
  missing value where TRUE/FALSE needed
Calls: pruneTree -> .validInput
In addition: Warning message:
In .validInput(key, "key", list("pruneTree", object)) :
  Key 'CHOIR' does not exist in provided object. If you want to use data generated by function buildTree(), make sure the key is the same.
Execution halted
```


CentOS Linux release 7.9.2009 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
CentOS Linux release 7.9.2009 (Core)

**Comment by catpetersen** [comment] 2024-03-09 00:39
> After benchmarking on a lot of precomputed clusters on scRNAseq and getting good results

Glad you're having good results using CHOIR!

> I tried setting downsampling_rate to zero but that gave an error. Apparently the number needs to be between 0 and 1.

Set `downsampling_rate` to 1 to disable downsampling. See details in this section of the tutorial: https://www.choirclustering.com/articles/CHOIR.html#downsampling

> I only have 2 features, so I just use them instead of the genes.

If you only have 2 features, I'm really not sure CHOIR is the best tool for this dataset. Random forest classifiers are typically used with a larger feature space.

> The error appears to be from the ranger function for the decision trees.

Does your input matrix have row & column names for the features & cells? If not, that might be causing the ranger error (see https://github.com/imbs-hl/ranger/issues/597)

**Comment by alifarhat40** [comment] 2024-03-09 00:51
Yes they have column names and row names for the feature and cells. The seurat preprocessing takes care of that. I think random forest should still be able to deal with just 2 features. Even if I increase the number of features to more than 2, I still get that error. The issue you shared also has just 2 features. I will keep debugging over the next few days to see if I can preprocess the data correctly. I will update you if I get it to work and share with you my benchmarking results. I think you developed an amazing tool and the community should certaily adopt it in their workflow. Statistical significance testing in hierarchical trees is the way to go.

**Comment by alifarhat40** [comment] 2024-03-27 23:15
I think the problem is that this method needs many features (columns) in general data that is not RNAseq. I tried a dataset with 18 features, it runs to 33% and it gives an error. So I guess the problem is that CHOIR needs really large datasets making it ideal for scRNA seq.

**Comment by alifarhat40** [comment] 2024-12-05 23:08
@catpetersen Have you tried using predefined labels with scATACseq data? So far it works great with scRNAseq based on your tutorial and guidance above, but the documentation for running CHOIR on scATACseq with predefined labels is unavailable. Thanks in advance!

**Comment by alifarhat40** [comment] 2025-03-11 22:51
@catpetersen On the same note, how about running CHOIR on pre-generated clusters from a multiomic dataset? For example, I have a lot of clusters from a multi-omic (scRNAseq and scATACseq) and want to use CHOIR based on your instructions in the tutorial [here](https://www.choirclustering.com/articles/CHOIR.html#using-choir-with-multi-modal-data). 

What would the workflow look like if I am interested in merging pregenerated clusters on such an object?

On a sub-note: parallel processing on pre-generated workflow does not work, and I am not convinced it works on the CHOIR function when running on all cells either.

**Comment by cathrinesant** [comment] 2025-04-22 08:20
Just getting to these comments -- the process for using CHOIR on predefined labels for an ATAC/multi-omic dataset shouldn't differ widely from doing this using RNA. But let me know if you run into specific errors.

Like I mentioned here https://github.com/corceslab/CHOIR/issues/26#issuecomment-2820418322, CHOIR for datasets containing ATAC-seq has been most thoroughly tested using ArchR objects, so there may be Signac-related issues that still need to be ironed out.
